---
-
  name: create virtaulhost {{conf_filename}} 
  template: src=vhost.conf.j2 dest={{conf_dir}}/{{conf_filename}} owner={{conf_owner}} group={{conf_group}} mode=0644

-
  name: enable site
  file: src={{ item.path }} dest={{ item.dest }} state=link
  when: conf_enabled_dir
  with_items:
    - { path: "{{conf_dir}}/{{conf_filename}}", dest: "{{conf_enabled_dir}}/{{conf_filename}}" }
